export const SET_DIRECTION_DATA = 'SET_DIRECTION_DATA';
export const SET_ORIGIN = 'SET_ORIGIN';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_POPUP_DATA = 'SET_POPUP_DATA';
export const SET_MAP_PARAMETERS = 'SET_MAP_PARAMETERS';

export const START_LOAD_DATA = 'START_LOAD_DATA';
export const SUCCESS_LOAD_DATA = 'SUCCESS_LOAD_DATA';
export const FAIL_LOAD_DATA = 'FAIL_LOAD_DATA';
